import React from 'react'

const page2 = () => {
  return (
    <div className='bg-[#010101] text-white border-2 border-amber-400'> 
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga veniam modi similique maxime voluptas, nesciunt architecto eligendi quaerat quia fugit. Reiciendis nulla eveniet, mollitia eius voluptatibus iure expedita libero officiis!

      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab sunt fugit officia doloribus. Illo repellat aut laboriosam iure earum placeat, molestias quas repudiandae maxime veritatis recusandae. Quis nihil omnis pariatur!
      Eius vitae iusto reprehenderit soluta dicta nisi, consequatur cumque accusantium deserunt, autem neque voluptatibus illum. Quos, esse nesciunt fuga rerum repellat consequuntur fugiat. Animi harum pariatur consequatur quasi earum rem?
      Eos alias ipsam, ea totam dolorum doloremque nesciunt explicabo fugiat. Corrupti recusandae doloribus neque necessitatibus quisquam eum harum accusantium odit nam dignissimos cum sint impedit, adipisci quidem cupiditate corporis nulla.
      Laudantium temporibus minus sed deleniti libero vitae ea possimus ullam odit qui tempora quo sunt, quia aperiam ex ipsum fuga quibusdam at porro omnis nulla dolorem quae. Beatae, adipisci praesentium!
      Totam nihil esse accusantium consequatur veritatis vero quae dignissimos pariatur ea iusto ipsam, doloremque ipsa sed dolores mollitia recusandae minus fuga iure qui soluta facilis unde? Eos sequi ut distinctio!
      Delectus praesentium a eaque rem cum maiores, culpa omnis consequatur, suscipit commodi laborum possimus voluptatum vitae facilis, deserunt quidem tempora quibusdam officiis unde iusto dicta repudiandae exercitationem quas ea! Ad.
      Praesentium impedit similique eveniet illo vitae distinctio laborum exercitationem a minus numquam? Eaque fuga doloremque minus voluptatibus ea ipsam similique quos aliquam, itaque cum animi veniam id nemo corporis quas.
      Sit sunt iusto, cumque accusantium dicta provident! Eum cumque, qui nisi exercitationem earum vel obcaecati tenetur rem est sed incidunt illum cupiditate nihil, distinctio dolore dolorum voluptatem at ut veritatis.
      Tenetur cumque quas tempora, blanditiis debitis eligendi aperiam impedit laboriosam in repellat necessitatibus cupiditate at, nihil quasi asperiores vitae est ullam ea consectetur iste perferendis modi ratione. Exercitationem, adipisci enim?
      Nisi, debitis qui repellat facilis ipsam quaerat facere adipisci eligendi? Totam, non quod, porro odio consequuntur at, quae mollitia distinctio ab nesciunt possimus est recusandae hic nam atque. Officia, similique?
      Impedit corporis iusto quo, magnam dolor aut consequuntur eius! Nam doloremque omnis, adipisci alias delectus, optio doloribus necessitatibus earum animi labore architecto tenetur saepe natus ipsum eos, magnam libero? Quidem!
      Atque dignissimos cupiditate culpa, sit incidunt sed, deleniti, quibusdam optio consectetur maiores quaerat eius nisi dolorum ea facilis. Veritatis cumque tenetur ut quae, illum eligendi consequatur error impedit exercitationem laboriosam.
      Soluta deserunt maiores expedita, minima illum laborum, aperiam earum officiis non ducimus dolores natus vero consequatur rem quod porro, dolor omnis repellendus modi. Reiciendis voluptatem a culpa, necessitatibus perspiciatis vero!
      Doloremque dolores molestiae alias natus beatae voluptatum corporis molestias fugit harum earum quo expedita illum voluptas ad quibusdam perspiciatis reprehenderit nesciunt, deserunt optio. Rerum excepturi, ab nobis quae dolores minus?
      Dolorem odio, laudantium hic facere voluptatum modi consectetur labore blanditiis! Placeat iste, dolores aliquam veritatis nihil repellat est recusandae quas? Molestiae exercitationem, accusantium ad dolor veritatis enim porro incidunt officiis.
      Incidunt quas dignissimos amet consectetur, debitis soluta, hic quam similique accusantium sapiente voluptatum magnam optio iusto impedit? Modi accusantium reiciendis, totam dolorem sequi, inventore recusandae harum ipsam dignissimos laudantium dolorum!
      Sint sunt voluptates veritatis animi ipsum esse similique, et autem dolores alias optio architecto odit. Soluta eveniet ducimus, repudiandae quisquam commodi magnam esse reprehenderit labore illo, quae odit atque dignissimos.
      Enim rem minus consequuntur facere deleniti vero dolores recusandae officia reprehenderit aut eligendi consectetur incidunt dicta eum aliquam nihil, sit delectus cupiditate corrupti repellat suscipit. Iste expedita dicta voluptas aliquid.
      Dignissimos adipisci, mollitia, placeat ipsa in, quos odit sunt facere fuga dolores sed incidunt dolorem molestiae distinctio illum vitae? Et dicta porro nihil asperiores nisi quas aliquam similique, corrupti non?
      Officiis adipisci eaque itaque iure provident voluptatum magnam ipsa quisquam, dolor odio saepe repudiandae quae vel error inventore est accusamus, dolores ab odit cumque. Voluptas labore ut aut autem reiciendis!
      Quam unde ducimus exercitationem doloribus sunt nihil quasi culpa vel quisquam mollitia laboriosam beatae facere esse atque praesentium totam nemo, necessitatibus ipsam quibusdam facilis quaerat debitis officia! Inventore, consectetur culpa.
      Labore totam ipsa, pariatur esse accusantium nemo optio laudantium magnam inventore a consectetur temporibus praesentium voluptatem beatae quisquam aspernatur ad voluptatum! Dignissimos commodi illo veritatis quo. In voluptatem asperiores quibusdam.
      Voluptas optio repudiandae consectetur magnam, vel harum. Incidunt praesentium minima placeat saepe vitae fugit, quia repellendus reiciendis nesciunt quo cum veritatis iusto tempore laborum tenetur nam corrupti at ullam! Voluptates.
      Mollitia, quaerat et? Eligendi, consectetur eos hic ratione nesciunt labore commodi fugiat ab odit amet repellendus laudantium repellat totam vero adipisci porro voluptatum enim vel voluptas? Repellendus eligendi error aliquam!
      Delectus sit, officiis accusantium velit odio aliquid illum tempora molestias asperiores numquam tempore optio eum neque possimus explicabo sapiente nam est architecto modi cum labore quis. Quod excepturi tempora quibusdam?
      Aperiam, veniam provident sed, voluptatem nam ad iusto recusandae ratione reiciendis natus placeat temporibus alias, possimus quo odit illum atque unde quam obcaecati exercitationem id. Quod esse voluptate earum dolore?
      Enim, tempora voluptates aliquam quisquam possimus fuga consectetur iste quaerat eligendi alias ipsum quidem delectus qui, commodi magni ad asperiores optio illum itaque rem ea. Velit mollitia beatae incidunt perferendis.
      Animi amet labore soluta sint culpa, velit assumenda? Natus at accusamus voluptatibus vitae aliquid ipsum perferendis esse. Libero itaque reiciendis facilis. Aut harum sequi deserunt, omnis provident eveniet voluptatum in.
      Autem cumque dolor sapiente ducimus repellat quae cupiditate corrupti ipsa facere eum! Hic atque, maxime vero nihil modi maiores reprehenderit alias at esse officiis doloribus unde iusto laboriosam temporibus similique.
      Accusamus cum suscipit perspiciatis mollitia repellat unde tempora iusto! Id eum autem animi. Assumenda alias mollitia dolor dolorum dolore quisquam a impedit veritatis, laboriosam ad nostrum quia labore consectetur nesciunt?
      Deleniti deserunt inventore expedita est eligendi debitis earum, laboriosam esse consectetur, dicta accusantium, doloremque tenetur! Dicta fugiat consequatur ullam porro necessitatibus reiciendis velit, aliquam illum et architecto eveniet unde accusantium.
      Autem quisquam corporis delectus facilis aliquid iure ullam! Soluta optio explicabo quia totam. Adipisci modi rem excepturi, dolorem explicabo ab deleniti quidem beatae sed omnis officiis, officia necessitatibus aspernatur. Numquam?
      Dicta eaque possimus minima vero ipsum repellendus ea dolorum quos, dolorem amet doloremque voluptatibus. Odit ea quis nulla minima expedita. Iure quasi quos dignissimos aspernatur eos cupiditate dolores suscipit repellat!
      Neque, rerum repudiandae dolor dolore facere pariatur ducimus aut molestias quidem accusantium doloremque obcaecati incidunt odio perferendis error perspiciatis harum magni consequuntur asperiores voluptatibus itaque nobis. Quaerat totam velit commodi.
      Soluta eius mollitia perferendis harum? Magni et qui labore, suscipit laboriosam assumenda, voluptates ea non deserunt, quasi maxime sapiente iusto ut doloremque voluptas laborum ratione! Architecto suscipit quod quos accusamus.
      Dicta nemo ducimus laborum natus facere repellat, laudantium voluptate illum autem harum reiciendis accusamus blanditiis porro iusto quasi quidem consequuntur magni ad nostrum provident voluptas quis distinctio at? Architecto, neque!
      Itaque incidunt officia totam quod suscipit laboriosam soluta voluptates, cumque in debitis vel dolorem mollitia aspernatur quae temporibus ea nemo aut quas neque vitae? Quo alias veniam excepturi incidunt quisquam?
      Nisi libero praesentium saepe ut, vel alias! Dignissimos, expedita ea eveniet odit soluta repellendus, minus delectus velit aliquid officia necessitatibus officiis tempora enim tenetur consequatur cum beatae eaque aspernatur id!
      Voluptatum, molestiae similique. Similique, fuga ipsam! Cumque accusamus corrupti, laboriosam laudantium aspernatur ex aperiam unde nostrum ipsum, doloribus quibusdam commodi velit saepe dolor. Illo fuga saepe aliquam adipisci quia animi.
      Cupiditate itaque odit maxime hic illum necessitatibus officiis veniam incidunt nulla nam a eius voluptatem fugit facere, dicta amet? A iure omnis magni esse dolor dicta! A rerum adipisci totam.
      Ullam vero quod consequuntur itaque cum ea quo placeat non reiciendis omnis, ab accusantium nemo nulla distinctio fuga, sequi voluptatibus sed repudiandae illo iusto odit. Dolorem vero placeat in optio.
      Possimus voluptate blanditiis eius corporis dolore, porro rem! Maxime voluptas fugit placeat at laboriosam perspiciatis odit fugiat doloribus quibusdam blanditiis voluptatum dolorem est illo dignissimos officia iure, consequatur inventore quod?
      Impedit ut ab incidunt pariatur, porro delectus quam explicabo doloremque eius, id fuga quas veritatis! Minus maxime, officia ad eum, sint omnis consequatur dolor, corporis autem itaque velit repellat dignissimos!
      Illum vitae impedit consectetur cumque tempora cum totam ex dolores quo odio blanditiis quos temporibus hic, consequatur ab eius, perferendis labore expedita. Dolore, natus. Doloribus, perspiciatis quia. Sint, reiciendis necessitatibus.
      Deserunt, dolorem labore et nesciunt cum sit dicta soluta facilis fugiat ea modi eaque culpa, iusto nostrum veniam? Dolorum tenetur quam voluptates, ratione commodi consequatur iste repellat quaerat minus dicta.
      Quisquam suscipit quia atque officiis. Quam aspernatur sit nam sapiente aut repellendus dolorem cum a doloremque ratione corporis recusandae ab ex dolore dolores et minima, deleniti ipsum modi atque est.
      Voluptatibus quas provident repellendus, aperiam molestiae aliquid eligendi distinctio numquam quae consequuntur, perferendis itaque commodi? Assumenda accusantium deserunt a quis tempora quo nobis qui est iusto natus. Deserunt, voluptates est!
      Quisquam ducimus officia pariatur quibusdam, placeat sunt optio dolor qui. Quis repellat soluta iusto! Eos incidunt, nemo cumque minima aspernatur accusantium, reiciendis sed fugiat necessitatibus aliquid quasi deleniti voluptatibus adipisci?
      Itaque, ipsam quos suscipit eius excepturi cumque perspiciatis rem est vel esse aperiam explicabo deleniti, dignissimos nobis accusantium commodi. Voluptates sapiente non, amet totam in doloremque velit. Ratione, tempora? Voluptatum?
      Impedit illo deleniti saepe id dolorum veniam distinctio iure explicabo consectetur quas eaque praesentium, dicta consequatur eos odit aspernatur quisquam necessitatibus perspiciatis itaque nisi dignissimos totam mollitia, repellat possimus! Fugit!
      Veritatis rerum vitae doloribus blanditiis quod corrupti. Perspiciatis commodi voluptas dolorem pariatur corrupti exercitationem, reiciendis, doloremque iste, adipisci cupiditate distinctio ducimus inventore! Dolore quae esse, aliquam modi nesciunt quaerat ea.
      Sint accusantium ut aspernatur soluta consectetur rem sapiente quod aliquam asperiores temporibus, hic amet obcaecati ducimus laboriosam, necessitatibus quo deleniti modi natus expedita illum incidunt? Amet aspernatur illum rerum soluta.
      Fugit corrupti similique porro pariatur placeat dignissimos, iure excepturi, adipisci ratione dicta accusamus quis voluptatibus illo esse nihil! Deserunt alias optio a officiis autem! Laboriosam necessitatibus error hic culpa praesentium?
      Quo reiciendis expedita sunt laboriosam maxime obcaecati incidunt similique porro recusandae provident dolorum, quisquam atque possimus a aperiam laborum animi unde fuga nemo odit perferendis harum enim nihil deleniti? Eos?
      Voluptates quam eaque fuga aliquid soluta officiis quis est reiciendis nesciunt sint temporibus rem, delectus aperiam, reprehenderit qui unde nihil repudiandae autem amet voluptatem labore quod, porro laudantium. Incidunt, vero!
      Dolorum, odio fugit. Dolor eligendi quaerat vitae voluptates, saepe facere magni aliquid animi deserunt nostrum praesentium blanditiis? Quo minus iusto ipsum? Iste, debitis atque! Repudiandae eveniet dolorem necessitatibus ipsa amet.
      Vel totam magni, debitis commodi aspernatur asperiores eos quo beatae est, ullam, dolorum error illum rerum. Illum laboriosam, eum possimus dolorem rerum omnis animi excepturi quam? Corporis nulla tempora repudiandae?
      Beatae, corporis aliquid! Esse quos itaque eaque dignissimos, dolorem quis facere provident dolore nobis. Eaque voluptatibus eveniet repudiandae non consequatur possimus. Reiciendis harum nemo minima necessitatibus delectus quia accusantium id!
      A veritatis porro eos alias veniam culpa velit mollitia ex atque, suscipit magni cupiditate ullam dolores ut enim architecto nam possimus, sapiente optio dicta. Assumenda expedita inventore labore neque consequuntur.
      Veritatis enim, soluta excepturi laboriosam laborum, veniam, unde sint nam atque beatae autem? Rem sapiente cupiditate necessitatibus dicta officia quisquam omnis quaerat dolores optio id libero reiciendis, quos minima explicabo.
      Molestiae unde laborum alias veniam labore facere, aperiam eligendi eum praesentium ratione deleniti earum, velit exercitationem in assumenda ducimus quos. Doloremque non laboriosam error reiciendis voluptates. Laboriosam harum veniam iure?
      Ratione error repellat et excepturi. Dolorem quaerat adipisci labore aliquam consectetur, repudiandae quidem et ea, maiores magnam facilis facere sunt molestiae saepe eaque rem temporibus autem cupiditate exercitationem, quas vitae?
      Inventore veniam beatae praesentium in! Amet quia rem in repudiandae nemo omnis maxime doloremque voluptatibus, accusamus facere beatae atque aut nobis. Qui commodi at, est illum a tempora fugit numquam.
      Unde, tenetur eius. Quos amet vero exercitationem recusandae, veritatis voluptas quaerat quasi, repudiandae cumque non neque aperiam incidunt aliquam iusto esse, tenetur temporibus illum voluptatem debitis dolore ipsa adipisci harum?
      Fugit assumenda pariatur, natus praesentium hic rerum illo nam iste rem tempora sit labore, ipsam minima. Et quisquam veniam, ex numquam esse sint hic ipsum, magni sapiente, dolor ab nemo?
      Quidem expedita blanditiis harum accusantium in quos fugiat, repudiandae quisquam culpa cupiditate distinctio molestiae ipsam aliquam velit? At quisquam facilis reiciendis. Ratione unde at odio ipsum quae quibusdam optio commodi?
      Sint odit tempora aliquam, exercitationem obcaecati eveniet hic distinctio. Pariatur consequuntur delectus libero eos ipsam quis repellat, dignissimos natus eveniet magnam, est porro excepturi officia neque, velit enim facilis. Nihil.
      Enim perspiciatis libero repellendus possimus. Dolorem, ducimus ipsam dolorum quidem, quisquam facilis velit nihil eos illum fugiat incidunt! Esse id earum quaerat neque dolorum tempora natus quas aliquid repellat nesciunt?
      Repellat vitae soluta minima, fuga voluptatem ex doloremque corrupti quis natus ad accusamus voluptates incidunt, assumenda cum numquam qui iste, rem quisquam sequi reiciendis voluptate! Esse doloremque totam molestiae est?
      Consequuntur officia repellendus, ab, assumenda perspiciatis aperiam iure reprehenderit iusto sunt repudiandae cum. Mollitia quidem fuga iure, ad nobis illo dignissimos delectus? Et soluta obcaecati voluptate consequatur cumque? Pariatur, possimus.
      Ipsam, aperiam molestiae! At dicta hic recusandae in debitis sit atque, fugiat quaerat molestias, ex odio officiis harum laudantium. Iusto, ea. Similique sapiente illum placeat illo, aperiam atque excepturi ab.
      Earum sit voluptatibus, placeat velit facere ipsum vitae. Est, ipsa ex ipsam placeat numquam dignissimos fuga laborum odio error temporibus quidem adipisci, dolore facere saepe qui laudantium tempora quibusdam alias.
      Tempora dolore reprehenderit, ducimus dolores ea exercitationem quae. Optio laudantium illum repellendus nihil iure praesentium, sed doloremque nam sequi esse placeat animi ipsam. Rem quasi dignissimos magnam adipisci, omnis mollitia?
      Architecto blanditiis illo, ratione tempore unde suscipit officiis minima enim, soluta possimus voluptatum reiciendis! Autem fuga, non dolore doloribus numquam facilis. Commodi illum cum, in possimus doloremque iure ipsa officia!
      Doloremque tempora illo dicta totam corrupti, alias ipsam necessitatibus voluptates a officia tempore itaque nesciunt delectus impedit, facere repellat nulla laborum unde. Corrupti minus modi expedita eveniet, quos nulla quod?
      Eum corrupti aliquam nisi eos ea nesciunt officia labore vitae dignissimos omnis temporibus laudantium rem est, unde fugit iste repudiandae maiores! Consectetur consequuntur, laboriosam ut minima perferendis tenetur amet blanditiis.
      Optio officiis nesciunt quasi vel ullam enim delectus maxime sint, at aut ad, beatae non nemo sequi quam pariatur nisi nam porro distinctio aspernatur saepe id neque in temporibus. At.
      Inventore aut nemo recusandae eveniet natus, atque, reiciendis ad repellendus assumenda totam reprehenderit voluptatum odit! Dolore consectetur dolor, modi in minima laudantium ipsam obcaecati voluptas vel quibusdam, labore, recusandae voluptates.
      Consectetur aspernatur nisi rem, incidunt, eos blanditiis, deleniti reprehenderit nam accusantium cumque officia aut alias repellendus facere nihil fugit ipsa natus dignissimos doloribus vitae odio fugiat non inventore. Eum, ex.
      Rerum nostrum unde ea nisi quia fuga aut voluptatum officia! Aliquam, ducimus. Rem facere exercitationem, eveniet labore adipisci voluptate natus eligendi aut repudiandae omnis. Nemo laborum in illo sit ab!
      Aperiam, id sit assumenda perspiciatis temporibus fugit error omnis est repellat et veritatis laboriosam neque voluptatum ipsum nam consequatur officia labore iusto! Nam cupiditate non aliquid. Nam quibusdam et nesciunt.
      Exercitationem, blanditiis? Porro repellat numquam voluptas amet quidem. Iste, nam corrupti sed perferendis, minus beatae optio ducimus animi doloremque atque sit! Sed corporis vero cum. Eos voluptates omnis consequuntur est?
      Maiores, rem doloribus. Harum commodi tempora est asperiores officiis, nobis ipsa, at animi architecto eum ea molestias itaque, facere molestiae corporis eligendi sint vel voluptatem delectus enim libero expedita ipsam?
      Quo doloremque excepturi itaque nesciunt quas, officiis minima, explicabo voluptatem rerum atque quod eaque a earum fugit est soluta autem ipsum minus? Culpa quae, corrupti voluptates quidem doloribus numquam nobis?
      Placeat sed distinctio nobis fugit quos quidem dignissimos temporibus, nostrum adipisci cum nesciunt aperiam dolorum natus deleniti, autem consequuntur, earum ea veniam possimus. Totam, enim aliquid. Similique laborum odit quisquam!
      Similique placeat ipsam aut enim voluptas exercitationem vitae explicabo quod perspiciatis? Molestias beatae sapiente omnis eius officia. Unde, quis veritatis voluptates error, omnis voluptatum tenetur, velit fugit impedit nihil labore.
      Necessitatibus, tenetur? Ab atque alias repellendus temporibus odit placeat itaque fugit error dolor harum, velit esse blanditiis sunt excepturi? Non voluptatibus soluta, officia aliquam quasi a doloribus similique itaque nihil.
      Omnis quae ipsum ullam nostrum hic nisi id est a placeat recusandae aspernatur sunt voluptatibus ut porro rerum at enim cum maiores necessitatibus, perferendis magnam. In inventore eum tempora nemo.
      Labore at rerum reprehenderit aspernatur voluptate enim excepturi velit in. Officiis accusamus fugit quibusdam facilis odit suscipit aliquam blanditiis quaerat, laborum excepturi non tempora amet ipsum nobis? Vero, laborum repellat.
      Voluptatem, consectetur illo. Officia maxime officiis esse suscipit dolorem dolor nisi repellendus facilis perspiciatis iusto ullam tempora exercitationem dignissimos incidunt laboriosam, blanditiis amet. Dolor veritatis enim odit assumenda blanditiis facere?
      Molestias, culpa dolorum voluptates iure dolor magnam, quisquam distinctio, ipsum deleniti excepturi quibusdam quaerat ipsa quo vero iste omnis exercitationem! Magnam iusto quia commodi perspiciatis obcaecati, debitis ullam saepe architecto.
      Beatae repellendus consequatur magni laborum necessitatibus enim debitis sit mollitia maxime eius, ipsa tempora nam, nulla accusantium, quidem nesciunt dolor deleniti. Nisi dolores omnis incidunt ipsa ullam facilis, earum rem.
      Itaque impedit quas explicabo dolor alias vel praesentium, tempora commodi libero et distinctio repudiandae ad odio, maiores a architecto! Explicabo blanditiis dolorum ratione. Nihil quae deserunt rem, non minima iure.
      Perferendis officiis a nisi laboriosam delectus atque adipisci vero ullam laudantium vel? Quisquam, laudantium quo! Quisquam fugiat sequi deleniti placeat neque, maxime impedit, consequatur praesentium laudantium, nam esse asperiores delectus.
      Itaque maxime aperiam modi dolore ipsum nisi porro repellendus enim esse, tempora hic aliquid ipsam laboriosam facilis officia necessitatibus incidunt illum quis. Nostrum, corporis! Perspiciatis est sequi quidem dolorem praesentium?
      Quod, soluta illo, nemo perferendis placeat odit aperiam tempore natus iste dolor accusamus id nihil harum blanditiis voluptas cumque? Recusandae libero quod, ea odit quos eos cupiditate beatae cumque in!
      Libero totam nesciunt ea amet assumenda iusto eaque commodi, dicta officia consequuntur. Cum ratione dicta sit sint laboriosam esse placeat delectus maiores laborum sequi praesentium atque, nulla consequatur numquam similique.
      Voluptates recusandae labore exercitationem dignissimos, dolores vitae dolorem doloremque, iste veniam aliquid nulla sit necessitatibus placeat odit excepturi ad perferendis porro inventore quo! Reprehenderit, sunt nihil sapiente ad laboriosam possimus.
      Ea assumenda nam dolor perferendis officia ipsam tempora delectus sequi pariatur nostrum recusandae odio totam, voluptatem labore suscipit, saepe ratione odit mollitia dicta, eligendi iusto asperiores praesentium consequuntur. Accusamus, consequuntur!
      Consequuntur assumenda distinctio et enim inventore, tenetur animi temporibus perferendis. Quibusdam sint nesciunt asperiores dolor! Ducimus quod numquam iusto, laborum ea distinctio facilis reiciendis animi itaque totam esse enim nisi.
    </div>
  )
}

export default page2

